Cf feature/event data
goerli/GoethWebsite pull request #2
Opened 2018-11-16 18:04 UTC by CFDevelopment

- Deposit and Withdraw events displayed
- Progress component for event feedback

2018-11-16 19:12 UTC, 5chdn commented on LICENSE
> +>>>>>>> 1318cf2e6b607c3a2ded2b0bc038c656ba2a4c8d
unresolved conflict committed

2018-11-16 19:16 UTC, CFDevelopment commented on LICENSE
> +>>>>>>> 1318cf2e6b607c3a2ded2b0bc038c656ba2a4c8d
@5chdn resolved

2018-11-16 22:24 UTC, ChainSafeSystems requested changes
please remove progress element before merge as we discussed.

2018-11-16 22:28 UTC, GregTheGreek requested changes

2018-11-16 22:28 UTC, GregTheGreek commented on src/screens/app/components/app/App.js
> +    const eventObject = { eventRecipient, eventValue, eventToChain, eventEvent, goerliRecipient, goerliValue, goerliFromChain, network };
this can be done in one line change `const` to `return`

2018-11-19 16:34 UTC, CFDevelopment commented on src/screens/app/components/app/App.js
> +    const eventObject = { eventRecipient, eventValue, eventToChain, eventEvent, goerliRecipient, goerliValue, goerliFromChain, network };
@GregTheGreek resolved

2018-11-19 16:36 UTC, merged