UI refactor - height on tx summary, href -> new tab. General UI tweaks
goerli/GoethWebsite pull request #6
Opened 2018-11-23 00:07 UTC by CFDevelopment

- general ui tweaks

2018-11-23 00:56 UTC, GregTheGreek requested changes
All good

2018-11-23 00:56 UTC, GregTheGreek commented on src/containers/bridge/components/TxSummary.js
> +  callback = (key) => {
these functions don't seem to be doing anything?

2018-11-23 01:06 UTC, CFDevelopment commented on src/containers/bridge/components/TxSummary.js
> +  callback = (key) => {
I added an input field for the data because it is long and if the overflow cuts the screen of the user might not be able to copy and paste all of its content. The fix was to create an input that they could copy and paste from, it needed an onchange function so I just created a placeholder to remove any errors. @GregTheGreek

2018-11-25 16:36 UTC, GregTheGreek approved these changes

2018-11-25 16:36 UTC, merged